name: Build Executables

on:
  push:
    branches: [FTR-12]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tkinter on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Install Tcl/Tk on macOS
        if: runner.os == 'macOS'
        run: |
          brew install tcl-tk
          echo "PATH=/opt/homebrew/opt/tcl-tk/bin:$PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/opt/tcl-tk/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/tcl-tk/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/tcl-tk/lib/pkgconfig" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile src/bserial/bserial.py --name bserial

      - name: Show build output
        run: |
          echo "Contents of dist/"
          ls -lh dist
          echo "Contents of build/"
          ls -lh build
        
      - name: Upload Executable
        uses: actions/upload-artifact@8e5e3cc29b8a020bb92bc3de0649462dbfce5f0e
        with:
          name: bserial-${{ runner.os }}
          path: dist/bserial*
